### PR TITLE
Implement From<char> for Str #2

### LINKED ISSUE #2: Implement `From<char` for `Str`
Add a `From<char>` and `From<&char>`

### PR DESCRIPTION
**Pull request by umaYnit**
Close #2.

### CODE REVIEW

**Review by kurtlawrence — CHANGES_REQUESTED** [review]
Thanks for the PR!

I am happy with your implementation, could you please just add a test which goes through some arbitrary characters and tests `Str` equality?
ie:
```rust
assert_eq!(Str::from('ß'), "ß");
// etc ...
```

**Comment by umaYnit** [comment]
Can I do this like:
```rust
 let s = Str::from('ß');
        match s.0 {
            Stack(_) => assert_eq!(&s, "ß"),
            _ => panic!("expecting this variant"),
        }

```

**Comment by kurtlawrence** [comment]
I'd rather it test against the public API since this is what library consumers would see. My code example should be sufficient.

**Review by kurtlawrence — CHANGES_REQUESTED** [review]
Those tests look good! Could you please make sure that the formatting passes with `cargo fmt -- --check`. Once the formatting passes, it should be good to be merged in!

**Review by kurtlawrence — APPROVED** [review]

**Pull request merged**
